kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8200
        hostPort: 8200
      - containerPort: 5432
        hostPort: 5432
      - containerPort: 9411
        hostPort: 9411