# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - id: generate-car
    binary: generate-car
    main: ./cmd/generate-car
    goos:
      - linux
      - windows
      - darwin
  - id: generate-ipld-car
    binary: generate-ipld-car
    main: ./cmd/generate-ipld-car
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
